/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#060e20",
        "surface-container-low":    "#131b2e",
        "surface-container":        "#171f33",
        "surface-container-high":   "#222a3d",
        "surface-container-highest":"#2d3449",
        "surface-bright":           "#31394d",
        "surface-variant":          "#2d3449",
        "surface-dim":              "#0b1326",
        "surface":                  "#0b1326",
        "background":               "#0b1326",
        "on-background":            "#dae2fd",
        "on-surface":               "#dae2fd",
        "on-surface-variant":       "#c2c6d6",
        "surface-tint":             "#adc6ff",
        "inverse-surface":          "#dae2fd",
        "inverse-on-surface":       "#283044",
        "outline":                  "#8c909f",
        "outline-variant":          "#424754",
        "primary":                  "#adc6ff",
        "primary-container":        "#4d8eff",
        "primary-fixed":            "#d8e2ff",
        "primary-fixed-dim":        "#adc6ff",
        "on-primary":               "#002e6a",
        "on-primary-container":     "#00285d",
        "on-primary-fixed":         "#001a42",
        "on-primary-fixed-variant": "#004395",
        "inverse-primary":          "#005ac2",
        "secondary":                "#b7c8e1",
        "secondary-container":      "#3a4a5f",
        "secondary-fixed":          "#d3e4fe",
        "secondary-fixed-dim":      "#b7c8e1",
        "on-secondary":             "#213145",
        "on-secondary-container":   "#a9bad3",
        "on-secondary-fixed":       "#0b1c30",
        "on-secondary-fixed-variant":"#38485d",
        "tertiary":                 "#ffb786",
        "tertiary-container":       "#df7412",
        "tertiary-fixed":           "#ffdcc6",
        "tertiary-fixed-dim":       "#ffb786",
        "on-tertiary":              "#502400",
        "on-tertiary-container":    "#461f00",
        "on-tertiary-fixed":        "#311400",
        "on-tertiary-fixed-variant":"#723600",
        "error":                    "#ffb4ab",
        "error-container":          "#93000a",
        "on-error":                 "#690005",
        "on-error-container":       "#ffdad6",
      },
      fontFamily: {
        headline: ["Outfit", "sans-serif"],
        body:     ["Outfit", "sans-serif"],
        label:    ["Outfit", "sans-serif"],
        mono:     ["'JetBrains Mono'", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm:   "0.125rem",
        md:   "0.25rem",
        lg:   "0.375rem",
        xl:   "0.75rem",
        "2xl":"1rem",
        full: "9999px",
      },
      boxShadow: {
        observatory: "0 20px 40px rgba(6, 14, 32, 0.4)",
        ambient:     "0 20px 40px rgba(6, 14, 32, 0.4)",
      },
    },
  },
  plugins: [],
}
